const fs = require('fs');

const trPath = 'src/messages/tr.json';
const enPath = 'src/messages/en.json';

const trData = JSON.parse(fs.readFileSync(trPath, 'utf8'));
const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));

trData.SrvCnc = {
  meta_title: "CNC İşleme | Sezkon – 5 Eksen CNC Frezeleme ve Torna",
  meta_desc: "5 eksen CNC frezeleme, CNC torna ve kompleks parça üretimi. Savunma sanayi, havacılık ve otomotiv için yüksek hassasiyetli CNC işleme.",
  bc_label: "CNC İşleme",
  hero_tag: "CNC & Lazer Kesim",
  hero_t1: "5 Eksen",
  hero_t2: "CNC Hassasiyet",
  hero_desc: "±0.005mm hassasiyetle 5 eksen simultane işleme kapasitemizle savunma sanayii, havacılık ve otomotiv sektörü için kompleks parçalar üretiyoruz.",
  btn_quote: "Fiyat Teklifi Al",
  btn_ref: "Referanslar",
  cap_t1: "CNC",
  cap_t2: "Üstünlüklerimiz",
  sec_tag: "Sektörler",
  sec_t1: "Hangi",
  sec_t2: "Sektörlere",
  sec_t3: "Hizmet Veriyoruz?",
  mat_tag: "Malzemeler",
  mat_t1: "İşlediğimiz",
  mat_t2: "Malzemeler",
  cta_t1: "STEP Dosyanızı Gönderin,",
  cta_t2: "24 Saatte Teklif Alın.",
  cta_desc: "Mühendis ekibimiz teknik inceleme yaparak en uygun işleme stratejisi ve fiyatı sunar.",
  cta_btn: "Teknik Teklif Al"
};

enData.SrvCnc = {
  meta_title: "CNC Machining | Sezkon – 5-Axis Milling and Turning",
  meta_desc: "5-axis CNC milling, turning, and complex part production for defense, aviation, and automotive.",
  bc_label: "CNC Machining",
  hero_tag: "CNC & Laser Cutting",
  hero_t1: "5-Axis",
  hero_t2: "CNC Precision",
  hero_desc: "With ±0.005mm precision and simultaneous 5-axis capability, we produce complex parts for defense, aviation, and automotive sectors.",
  btn_quote: "Get a Quote",
  btn_ref: "References",
  cap_t1: "Our CNC",
  cap_t2: "Advantages",
  sec_tag: "Sectors",
  sec_t1: "Which",
  sec_t2: "Sectors",
  sec_t3: "Do We Serve?",
  mat_tag: "Materials",
  mat_t1: "Materials",
  mat_t2: "We Process",
  cta_t1: "Send Your STEP File,",
  cta_t2: "Get a Quote in 24 Hours.",
  cta_desc: "Our engineering team conducts a technical review to offer the optimal machining strategy and pricing.",
  cta_btn: "Get Technical Quote"
};

trData.SrvSoft = {
  meta_title: "Özel Yazılım Geliştirme | Sezkon – Kurumsal Yazılım Çözümleri",
  meta_desc: "ERP, CRM, MES ve iş süreçlerinize özel yazılım geliştirme. Agile metodoloji, modern teknoloji yığını ve 7/24 destek ile kurumsal yazılım.",
  bc_label: "Özel Yazılım",
  hero_tag: "Yazılım Çözümleri",
  hero_t1: "İşletmeniz İçin",
  hero_t2: "Birebir Yazılım",
  hero_desc: "Hazır çözümlerin yetersiz kaldığı noktalarda devreye giriyoruz. İş süreçlerinizi tam olarak yansıtan, ölçeklenebilir özel yazılımlar geliştiriyoruz.",
  btn_quote: "Teklif Al",
  btn_ref: "Referanslar",
  feat_t1: "Çözüm",
  feat_t2: "Alanlarımız",
  stack_tag: "Teknoloji Yığını",
  stack_t1: "Kullandığımız",
  stack_t2: "Teknolojiler",
  proc_tag: "Agile Süreç",
  proc_t1: "Nasıl",
  proc_t2: "Çalışıyoruz?",
  cta_t1: "Projenizi",
  cta_t2: "Hayata Geçirelim.",
  cta_desc: "Ücretsiz ön analiz görüşmesi için bugün iletişime geçin.",
  cta_btn: "Ücretsiz Analiz"
};

enData.SrvSoft = {
  meta_title: "Custom Software Development | Sezkon – Enterprise Solutions",
  meta_desc: "Custom software development for ERP, CRM, MES. Enterprise software with Agile methodology and modern tech stack.",
  bc_label: "Custom Software",
  hero_tag: "Software Solutions",
  hero_t1: "Tailor-Made Software",
  hero_t2: "for Your Business",
  hero_desc: "We step in where off-the-shelf solutions fall short. We develop scalable custom software that perfectly reflects your business processes.",
  btn_quote: "Get a Quote",
  btn_ref: "References",
  feat_t1: "Our Solution",
  feat_t2: "Areas",
  stack_tag: "Tech Stack",
  stack_t1: "Our",
  stack_t2: "Technologies",
  proc_tag: "Agile Process",
  proc_t1: "How",
  proc_t2: "We Work",
  cta_t1: "Let's Bring",
  cta_t2: "Your Project to Life.",
  cta_desc: "Contact us today for a free preliminary analysis meeting.",
  cta_btn: "Free Analysis"
};

trData.SrvSheet = {
  meta_title: "Sac Lazer Kesim | Sezkon – Çelik ve Paslanmaz Çelik Lazer Kesim",
  meta_desc: "Siyah sac, paslanmaz çelik ve galvanizli sac lazer kesim hizmetleri. 30mm kalınlığa kadar yüksek hassasiyetli lazer kesim ve bükme.",
  bc_label: "Sac Lazer Kesim",
  hero_tag: "CNC & Lazer Kesim",
  hero_t1: "Sac Kesimde",
  hero_t2: "12kW Güç",
  hero_desc: "Siyah sac, paslanmaz çelik ve galvaniz malzemeleri 30mm kalınlığa kadar yüksek hassasiyetle kesiyor, istenildiğinde bükme ve kaynak hizmetleriyle destekliyoruz.",
  btn_quote: "Fiyat Teklifi Al",
  cap_t1: "Neden",
  cap_t2: "Sezkon?",
  mat_t1: "Malzeme",
  mat_t2: "Kapasitesi",
  col_mat: "Malzeme",
  col_thk: "Maks. Kalınlık",
  cta_t1: "Tekniğinizi Bize Gönderin,",
  cta_t2: "Anında Teklif Alın.",
  cta_desc: "DXF veya DWG dosyanızla iletişime geçin, mühendislerimiz en verimli kesim planını hazırlasın.",
  cta_btn: "Fiyat Teklifi Al"
};

enData.SrvSheet = {
  meta_title: "Sheet Metal Laser Cutting | Sezkon",
  meta_desc: "High-precision laser cutting up to 30mm for mild steel, stainless, and galvanized sheets.",
  bc_label: "Laser Cutting",
  hero_tag: "CNC & Laser Cutting",
  hero_t1: "12kW Power",
  hero_t2: "in Sheet Cutting",
  hero_desc: "We cut mild steel, stainless steel, and galvanized materials up to 30mm with high precision, backed by bending and welding services upon request.",
  btn_quote: "Get a Quote",
  cap_t1: "Why",
  cap_t2: "Sezkon?",
  mat_t1: "Material",
  mat_t2: "Capacity",
  col_mat: "Material",
  col_thk: "Max Thickness",
  cta_t1: "Send Us Your Blueprint,",
  cta_t2: "Get an Instant Quote.",
  cta_desc: "Contact us with your DXF or DWG file, and our engineers will prepare the most efficient cutting plan.",
  cta_btn: "Get an Instant Quote"
};

trData.SrvWeb = {
  meta_title: "Web Tasarım Hizmetleri | Sezkon – Kurumsal Web Çözümleri",
  meta_desc: "Kurumsal kimliğinizi yansıtan, SEO uyumlu ve yüksek performanslı web sitesi tasarımı. Next.js ve React ile modern web deneyimi.",
  bc_label: "Web Tasarım",
  hero_tag: "Yazılım Çözümleri",
  hero_t1: "Etkileyici",
  hero_t2: "Web Deneyimleri",
  hero_desc: "Markanızı dijital dünyada en iyi şekilde temsil eden, hızlı, SEO uyumlu ve dönüşüm odaklı web siteleri tasarlıyoruz.",
  btn_quote: "Teklif Al",
  btn_ref: "Referanslar",
  feat_t1: "Neden",
  feat_t2: "Sezkon Web?",
  feat_desc: "Rakiplerinizin önüne geçmeniz için ihtiyacınız olan her şey tek çatı altında.",
  proc_tag: "Sürecimiz",
  proc_t1: "Fikrden",
  proc_t2: "Yayına",
  pkg_tag: "Paketler",
  pkg_t1: "İhtiyacınıza",
  pkg_t2: "Uygun Paket",
  btn_start: "Başlayalım",
  badge_pop: "En Popüler",
  cta_t1: "Projenizi Hayata",
  cta_t2: "Geçirelim.",
  cta_desc: "Ücretsiz ön değerlendirme için formu doldurun, 24 saat içinde yanıt verelim.",
  cta_btn: "Ücretsiz Teklif Al"
};

enData.SrvWeb = {
  meta_title: "Web Design Services | Sezkon – Corporate Web Solutions",
  meta_desc: "Corporate, SEO-friendly, high-performance web design with Next.js and React.",
  bc_label: "Web Design",
  hero_tag: "Software Solutions",
  hero_t1: "Impressive",
  hero_t2: "Web Experiences",
  hero_desc: "We design fast, SEO-friendly, and conversion-oriented websites that represent your brand perfectly in the digital world.",
  btn_quote: "Get a Quote",
  btn_ref: "References",
  feat_t1: "Why",
  feat_t2: "Sezkon Web?",
  feat_desc: "Everything you need to stay ahead of the competition under one roof.",
  proc_tag: "Our Process",
  proc_t1: "From Idea",
  proc_t2: "to Launch",
  pkg_tag: "Packages",
  pkg_t1: "Packages That",
  pkg_t2: "Fit Your Needs",
  btn_start: "Get Started",
  badge_pop: "Most Popular",
  cta_t1: "Let's Bring Your Project",
  cta_t2: "to Life.",
  cta_desc: "Fill out the form for a free preliminary evaluation, and we'll reply within 24 hours.",
  cta_btn: "Get Free Quote"
};

trData.SrvApp = {
  meta_title: "Mobil Uygulama Geliştirme | Sezkon – iOS & Android Çözümleri",
  meta_desc: "React Native ile iOS ve Android için native performanslı mobil uygulama geliştirme. ERP, CRM ve kurumsal iş uygulamaları.",
  bc_label: "Mobil Uygulama",
  hero_tag: "Yazılım Çözümleri",
  hero_t1: "Yönetim",
  hero_t2: "Cebinizde",
  hero_desc: "İşletmenizin tüm süreçlerini cebinizden yönetin. React Native ile iOS ve Android için native performanslı kurumsal uygulamalar geliştiriyoruz.",
  btn_quote: "Teklif Al",
  feat_t1: "Kurumsal Mobil",
  feat_t2: "Güç",
  sec_tag: "Kullanım Alanları",
  sec_t1: "Hangi",
  sec_t2: "Sektörler",
  sec_t3: "İçin?",
  cta_t1: "Uygulamanız",
  cta_t2: "60 Günde",
  cta_t3: "Yayında.",
  cta_desc: "Hızlı prototipleme ile fikrinizi kısa sürede somut ürüne dönüştürüyoruz.",
  cta_btn: "Ücretsiz Danışma"
};

enData.SrvApp = {
  meta_title: "Mobile App Development | Sezkon – iOS & Android Solutions",
  meta_desc: "Native performance mobile app development for iOS and Android with React Native.",
  bc_label: "Mobile App",
  hero_tag: "Software Solutions",
  hero_t1: "Management",
  hero_t2: "in Your Pocket",
  hero_desc: "Manage all your business processes from your pocket. We build high-performance corporate apps for iOS and Android using React Native.",
  btn_quote: "Get a Quote",
  feat_t1: "Corporate Mobile",
  feat_t2: "Power",
  sec_tag: "Use Cases",
  sec_t1: "For Which",
  sec_t2: "Sectors?",
  sec_t3: "",
  cta_t1: "Your App",
  cta_t2: "in 60 Days",
  cta_t3: "Live.",
  cta_desc: "We turn your idea into a tangible product in a short time with rapid prototyping.",
  cta_btn: "Free Consultation"
};

trData.SrvEcom = {
  meta_title: "E-Ticaret Sistemleri | Sezkon – Güçlü Online Satış Altyapısı",
  meta_desc: "B2B ve B2C e-ticaret altyapısı, ödeme entegrasyonu, stok yönetimi ve mobil uyumlu online mağaza çözümleri. Satışlarınızı dijitale taşıyın.",
  bc_label: "E-Ticaret Sistemleri",
  hero_tag: "Yazılım Çözümleri",
  hero_t1: "Satışlarınızı",
  hero_t2: "Dijitale Taşıyın",
  hero_desc: "B2B ve B2C e-ticaret ihtiyaçlarının tamamını karşılayan, ölçeklenebilir ve güvenli satış platformları kuruyoruz.",
  btn_quote: "Teklif Al",
  feat_t1: "Eksiksiz",
  feat_t2: "E-Ticaret",
  feat_t3: "Çözümü",
  inc_tag: "Neler Dahil?",
  inc_t1: "Her Paketle Gelen",
  inc_t2: "Standart Özellikler",
  inc_desc: "İşletmenizi büyütmek için ihtiyaç duyduğunuz tüm altyapı hazır ve dahil.",
  cta_t1: "Online Mağazanızı",
  cta_t2: "Bugün Kurun.",
  cta_desc: "48 saat içinde canlı e-ticaret mağazanıza kavuşun.",
  cta_btn: "Ücretsiz Teklif Al"
};

enData.SrvEcom = {
  meta_title: "E-Commerce Systems | Sezkon",
  meta_desc: "B2B and B2C e-commerce infrastructure, payment integration, stock management.",
  bc_label: "E-Commerce",
  hero_tag: "Software Solutions",
  hero_t1: "Take Your Sales",
  hero_t2: "Digital",
  hero_desc: "We build scalable and secure sales platforms that meet all B2B and B2C e-commerce needs.",
  btn_quote: "Get a Quote",
  feat_t1: "Complete",
  feat_t2: "E-Commerce",
  feat_t3: "Solution",
  inc_tag: "What's Included?",
  inc_t1: "Standard Features",
  inc_t2: "with Every Package",
  inc_desc: "All the infrastructure you need to grow your business is ready and included.",
  cta_t1: "Launch Your Store",
  cta_t2: "Today.",
  cta_desc: "Get your live e-commerce store within 48 hours.",
  cta_btn: "Free Quote"
};

trData.SrvInd = {
  meta_title: "Endüstri 4.0 Çözümleri | Sezkon – Akıllı Fabrika ve IoT Entegrasyonu",
  meta_desc: "IoT sensör ağları, yapay zeka tabanlı kalite kontrol, OPC-UA protokolü ve dijital ikiz teknolojileriyle fabrikanızı geleceğe taşıyın.",
  bc_label: "Endüstri 4.0",
  hero_tag: "YENİ · Endüstri 4.0 Çözümleri",
  hero_t1: "Fabrikanızı",
  hero_t2: "Geleceğe Taşıyın",
  hero_desc: "IoT sensörleri, yapay zeka tabanlı kalite kontrol, dijital ikiz ve prediktif bakım teknolojileriyle üretim verimliliğinizi %25'e kadar artırın.",
  btn_quote: "Ücretsiz Değerlendirme",
  btn_ref: "Referanslar",
  sol_tag: "Çözümlerimiz",
  sol_t1: "Akıllı Fabrika",
  sol_t2: "Teknolojileri",
  road_tag: "Dönüşüm Yol Haritası",
  road_t1: "Adım Adım",
  road_t2: "Dijital Olgunluk",
  eco_tag: "Entegrasyon Ekosistemi",
  why_tag: "Neden Sezkon?",
  why_t1: "Hem Yazılım Hem",
  why_t2: "Üretim Bilgisi",
  why_d1: "Çoğu dijital dönüşüm firması yazılım biliyor ama üretimi bilmiyor; CNC firmaları üretimi biliyor ama yazılımı bilmiyor.",
  why_d2: "Sezkon her iki dünyada da uzman olan nadir firmalardandır. Fabrika zemini deneyimimiz, dijital çözümlerimizi gerçek ihtiyaçlara göre şekillendirir.",
  cta_tag: "ÜCRETSİZ DEĞERLENDİRME",
  cta_t1: "Fabrikanızın Dijital Olgunluğunu",
  cta_t2: "Ölçelim.",
  cta_desc: "Ücretsiz dijital olgunluk değerlendirmesi ile nerede olduğunuzu ve nereye gidebileceğinizi birlikte keşfedelim.",
  cta_btn: "Değerlendirme İste",
  cta_sub: "24 saat içinde yanıt · Ücretsiz · Taahhütsüz"
};

enData.SrvInd = {
  meta_title: "Industry 4.0 Solutions | Sezkon – Smart Factory & IoT",
  meta_desc: "IoT sensor networks, AI-based quality control, OPC-UA protocol, and digital twin technologies.",
  bc_label: "Industry 4.0",
  hero_tag: "NEW · Industry 4.0 Solutions",
  hero_t1: "Take Your Factory",
  hero_t2: "to the Future",
  hero_desc: "Increase your production efficiency by up to 25% with IoT sensors, AI-based quality control, digital twins.",
  btn_quote: "Free Evaluation",
  btn_ref: "References",
  sol_tag: "Our Solutions",
  sol_t1: "Smart Factory",
  sol_t2: "Technologies",
  road_tag: "Transformation Roadmap",
  road_t1: "Step by Step",
  road_t2: "Digital Maturity",
  eco_tag: "Integration Ecosystem",
  why_tag: "Why Sezkon?",
  why_t1: "Both Software and",
  why_t2: "Manufacturing Expertise",
  why_d1: "Most digital transformation companies know software but not manufacturing; CNC companies know manufacturing but not software.",
  why_d2: "Sezkon is one of the rare companies expert in both worlds. Our shop floor experience shapes our digital solutions to real needs.",
  cta_tag: "FREE EVALUATION",
  cta_t1: "Let's Measure Your Factory's",
  cta_t2: "Digital Maturity.",
  cta_desc: "Let's discover together where you are and where you can go with a free digital maturity assessment.",
  cta_btn: "Request Evaluation",
  cta_sub: "Reply in 24 hours · Free · No Commitment"
};

trData.SrvBend = {
  meta_title: "Abkant Büküm | Sezkon – CNC Press Brake Hizmetleri",
  meta_desc: "CNC abkant pres ile hassas sac büküm hizmetleri. 320 ton kapasiteli preslerde ±0.2° açı toleransı ile tek ve çok operasyonlu büküm.",
  bc_label: "Abkant Büküm",
  hero_tag: "CNC & Lazer Kesim",
  hero_t1: "320 Tonluk",
  hero_t2: "Büküm Gücü",
  hero_desc: "320 ton kapasiteli CNC abkant preslerde ±0.2° açı toleransıyla karmaşık profilleri tek seferde üretiyor, lazer kesim ile entegre hizmet sunuyoruz.",
  btn_quote: "Fiyat Teklifi Al",
  cap_t1: "Abkant",
  cap_t2: "Yeteneklerimiz",
  prof_tag: "Profil Çeşitleri",
  prof_t1: "Ürettiğimiz",
  prof_t2: "Profiller",
  prof_desc: "Standart profillerin yanı sıra teknik çiziminize uygun özel form profilleri de üretiyoruz.",
  cta_t1: "Lazer + Büküm Kombine",
  cta_desc: "Lazer kesim ve abkant büküm işlemlerinizi tek bir firmada birleştirin. Ekstra taşıma maliyeti, geçiş süresi ve koordinasyon yükü olmadan.",
  cta_btn: "Teklif Al"
};

enData.SrvBend = {
  meta_title: "Bending | Sezkon – CNC Press Brake Services",
  meta_desc: "Precision sheet metal bending with CNC press brake. Tolerances of ±0.2° with 320-ton capacity presses.",
  bc_label: "Bending",
  hero_tag: "CNC & Laser Cutting",
  hero_t1: "320-Ton",
  hero_t2: "Bending Power",
  hero_desc: "We produce complex profiles with ±0.2° angle tolerance using our 320-ton CNC press brakes, offering integrated laser cutting services.",
  btn_quote: "Get a Quote",
  cap_t1: "Our Bending",
  cap_t2: "Capabilities",
  prof_tag: "Profile Types",
  prof_t1: "Profiles",
  prof_t2: "We Produce",
  prof_desc: "In addition to standard profiles, we produce custom form profiles tailored to your technical drawings.",
  cta_t1: "Laser + Bending Combined",
  cta_desc: "Combine your laser cutting and bending processes in one company. No extra shipping costs, transfer times, or coordination hurdles.",
  cta_btn: "Get Quote"
};

trData.SrvAlum = {
  meta_title: "Alüminyum Lazer Kesim | Sezkon – Endüstriyel Lazer İşleme",
  meta_desc: "Yüksek hassasiyetli alüminyum lazer kesim hizmetleri. 0.05mm tolerans, hızlı teslimat ve rekabetçi fiyatlarla endüstriyel alüminyum işleme.",
  bc_label: "Alüminyum Lazer Kesim",
  hero_tag: "CNC & Lazer Kesim",
  hero_t1: "Alüminyumda",
  hero_t2: "Mikron Hassasiyet",
  hero_desc: "6000W fiber lazer kesim teknolojimizle alüminyum parçalarınızı ±0.05mm hassasiyetle, oksit serbest yüzey kalitesiyle işliyoruz.",
  btn_quote: "Fiyat Teklifi Al",
  cap_t1: "Neden",
  cap_t2: "Sezkon Lazer?",
  mat_tag: "Malzeme Yelpazesi",
  mat_t1: "Hangi",
  mat_t2: "Alüminyum Serilerini",
  mat_t3: "İşliyoruz?",
  mat_desc: "Havacılıktan denizcilik sektörüne, yapısal uygulamalardan savunma sanayiine geniş bir alüminyum alaşım yelpazesini işleyebiliyoruz.",
  cta_t1: "Tekniğinizi Gönderin,",
  cta_t2: "24 Saatte Teklifini Alın.",
  cta_desc: "DXF, DWG veya STEP dosyanızı ekleyin, mühendislerimiz en uygun çözümü sunsun.",
  cta_btn: "Fiyat Teklifi Al"
};

enData.SrvAlum = {
  meta_title: "Aluminum Laser Cutting | Sezkon – Industrial Laser Processing",
  meta_desc: "High-precision aluminum laser cutting services. Industrial aluminum processing with 0.05mm tolerance.",
  bc_label: "Aluminum Laser Cutting",
  hero_tag: "CNC & Laser Cutting",
  hero_t1: "Micron Precision",
  hero_t2: "in Aluminum",
  hero_desc: "With our 6000W fiber laser technology, we process your aluminum parts with ±0.05mm precision and oxide-free surface quality.",
  btn_quote: "Get a Quote",
  cap_t1: "Why",
  cap_t2: "Sezkon Laser?",
  mat_tag: "Material Range",
  mat_t1: "Which",
  mat_t2: "Aluminum Series",
  mat_t3: "Do We Process?",
  mat_desc: "From aerospace to marine, structural applications to defense, we process a broad range of aluminum alloys.",
  cta_t1: "Send Your Drawing,",
  cta_t2: "Get Quote in 24h.",
  cta_desc: "Attach your DXF, DWG, or STEP file, and our engineers will offer the optimal solution.",
  cta_btn: "Get Quote"
};

fs.writeFileSync(trPath, JSON.stringify(trData, null, 2));
fs.writeFileSync(enPath, JSON.stringify(enData, null, 2));
console.log('Dictionaries updated successfully.');
